# Generated by Django 4.1.7 on 2023-03-16 23:50

from django.db import migrations, models
import general.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nacimiento', models.DateField(help_text='Fecha de Nacimiento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], help_text='M: Masculino, F: Femenino', max_length=1)),
            ],
            bases=(models.Model, general.models.Persona),
        ),
    ]
