# Generated by Django 4.1.7 on 2023-03-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('nacimiento', models.DateField()),
                ('muerte', models.DateField(blank=True, null=True, verbose_name='Fallecido')),
            ],
        ),
    ]
