# Generated by Django 4.1.7 on 2023-03-18 15:47

from django.db import migrations, models
import general.models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='autores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacimiento', models.DateField()),
                ('muerte', models.DateField(blank=True, null=True, verbose_name='Fallecido')),
            ],
            bases=(models.Model, general.models.Persona),
        ),
    ]
