# Generated by Django 4.1.7 on 2023-03-21 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del género (ej: Ciencia Ficción, Poesía, Fantasía, etc)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, unique=True)),
                ('resumen', models.TextField(help_text='Ingrese un breve resumen del libro', max_length=1000)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.autor')),
                ('genero', models.ForeignKey(help_text='Seleccione un genero para el libro', null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.genero')),
            ],
        ),
    ]
