# Generated by Django 4.1.7 on 2023-03-18 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_generos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50, unique=True)),
                ('resumen', models.TextField(help_text='Ingrese un breve resumen del libro', max_length=1000)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.autores')),
                ('genero', models.ManyToManyField(help_text='Seleccione un genero para el libro', to='general.generos')),
            ],
        ),
    ]
